gesdinet_jwt_refresh_token:
    refresh_token_class: App\Core\Persistence\Entity\RefreshToken
    return_expiration: true
    return_expiration_parameter_name: refresh_token_expired_at
    ttl_update: true
