security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Core\Persistence\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        not_secure:
            pattern: ^/api/v(\d+)/authorization/(register|restore_password|check_reset_token|change_password)
            stateless: true
            lazy: true
            provider: app_user_provider

        authorization:
            pattern: ^/api/v(\d+)/authorization/login
            stateless: true
            lazy: true
            provider: app_user_provider

            json_login:
                check_path: v1_authorization_login

            custom_authenticators:
                - App\Core\Symfony\Security\CustomJsonLoginAuthenticator

        main:
            lazy: true
            provider: app_user_provider
            jwt: ~

            logout:
                path: v1_authorization_logout

    access_control:
        - { path: ^/api/v(\d+)/authorization/(login|register|restore_password|check_reset_token|change_password), roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
