version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx/development
    volumes:
      - .:/app
    depends_on:
      - database
      - php-fpm
    ports:
      - "8083:80"
    networks:
      database:
      php-fpm:
      mailer:
  php-fpm:
    build:
      context: ./docker/php-fpm/development
    environment:
      MAIL_DEFAULT_FROM: ${MAIL_DEFAULT_FROM}
      MAIL_HELP_EMAIL: ${MAIL_HELP_EMAIL}
    volumes:
      - .:/app
    depends_on:
      - database
    ports:
      - "9000:9000"
    networks:
      database:
      php-fpm:
      mailer:
  php-cli:
    build:
      context: ./docker/php-cli/development
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      MAIL_DEFAULT_FROM: ${MAIL_DEFAULT_FROM}
      MAIL_HELP_EMAIL: ${MAIL_HELP_EMAIL}
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
    depends_on:
      - database
    networks:
      database:
  database:
    build:
      context: ./docker/postgres/development
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./docker/postgres/development:/docker-entrypoint-initdb.d
      - ./database:/var/lib/postgresql/data:rw
    ports:
      - "15434:5432"
    networks:
      database:
###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
    networks:
      mailer:
###< symfony/mailer ###

volumes:
  composer:
  database:

networks:
  database:
  php-fpm:
  mailer:
