controllers:
    resource: ../src/Core/Presentation/Controller/
    type: attribute

v1_authorization_login:
    path: /api/v1/authorization/login

v1_authorization_refresh_token:
    path: /api/v1/authorization/refresh_token
